<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Asynchronous JavaScript</title>
</head>
<body>
    <h1>Asynchronous JavaScript</h1>
    <script>		
		const getIDs = new Promise((resolve, reject) => {
			setTimeout(() => {
				resolve([523, 883, 432, 974]);
			}, 1500);
		
		});
					
		/*
		//demo of reject & error catch
		const getIDs2 = new Promise((resolve, reject) => {
			setTimeout(() => {
				reject([121, 312, 987, 456]); // mark this promise as an error
			}, 1500);
		
		});
	
		// handling the fulfilled/resolved promises
		getIDs2
		.then(IDs => {
			console.log('Demo with "reject" & "then"');
			console.log('"then" will not trigger as it is a reject call');		
			console.log(IDs);
		})
		.catch(error => {
			console.log('Demo with "reject" & "then"');
			console.log('"catch" will trigger as it is a reject call');		
			console.log(error);
		});	
		*/
		// demo with recipe example
		const getRecipe = recID => {
			return new Promise((resolve, reject) => {
				setTimeout(ID => {
					const recipe1 = {title:'Fresh Tomato Pasta',
									 publisher: 'Jonas'};
					resolve(`${ID}: ${recipe1.title}`);
				}, 1500, recID);					
			
			});
		
		};
		
		const getRelated = publisher => {
			return new Promise((resolve, reject) => {
				setTimeout(publ => {
					const recipe2 = {title: 'Italian Pizza',
									 publisher: 'Mark'};
					resolve(`${publ}: ${recipe2.title}`);
				
				}, 1500, publisher);
			});
		
		};

		// handling the fulfilled/resolved promises
		// this section will consume promises of both "getIDs" & "getRecipe"
		getIDs
		.then(IDs => {
			console.log('Demo with "resolve" & "then" & "catch"');
			console.log('Consuming the promise w.r.t. "getIDs" & return as consuming of "getRecipe"');
			console.log(IDs);
			console.log('Calling the "getRecipe" promise');
			return getRecipe(IDs[2]);
		})
		.then(recipe => {
			console.log();
			console.log('Consuming the promise w.r.t. "getRecipe"');
			console.log(recipe);
			console.log('Calling the "getRelated" promise');
			//Could not call "recipe.publisher" as "getRecipe" returns a string not an object
			//return getRelated(recipe.publisher);			
			return getRelated('Mark');			
		})
		.then(publisher => {
			console.log();
			console.log('Consuming the promise w.r.t. "getRelated"');
			console.log(publisher);
		})	
		.catch(error => {
			console.log(error);
		});	
		
		
		

		
    </script>
</body>
</html>
